### ISSUE TITLE
Prevent creation of empty entries

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#40]
Prevent unnecessary creation of empty entries (no text and no pictures, tags with no pics or text still count as an empty entry) by users intuitively and not obstructively. 

[Will post full description of behaviour soon]

**Comment by sguergachi** [comment]
1. create an empty entry
2. press the create entry button repeatedly in quick succession
3. crash

Exception:

        System.IO.IOException: The process cannot access the file 'C:\Users\Sammy\Dropbox\Apps\Day One\Journal.dayone\entries\204C5E7232504B1484736F997C336B05.doentry' because it is being used by another process.
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.FileInfo.Delete()
        at Journaley.Core.Models.Entry.Delete(String folderPath) in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley.Core\Models\Entry.cs:line 594
        at Journaley.Forms.MainForm.AddNewEntry() in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Forms\MainForm.cs:line 1049
        at Journaley.Forms.MainForm.ButtonAddEntry_Click(Object sender, EventArgs e) in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Forms\MainForm.cs:line 1731
        at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
        at System.Windows.Forms.Control.WndProc(Message& m)
        at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by yyoon** [comment]
Can you reproduce this bug consistently? I never see that exception no matter how fast I click the button repeatedly.

**Comment by sguergachi** [comment]
Yeah, It happens when Dropbox is running, likely when it's syncing or doing something concurrently with journaley creating a new entry.

Since it's an edge case, maybe just handling it in a graceful way so it doesn't crash is enough for now.

**Comment by yyoon** [comment]
#4e5a153 This should fix this problem, in theory. I added a try-catch block there, so it doesn't show the unhandled exception dialog, even when there is an error.
