### ISSUE TITLE
January 0001 empty entries created.

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#72]
These entries are created upon use of Journaley. They are shown on the Day One iOS app diffrently however. The cause and reproduction steps are still unknown.

![image](https://cloud.githubusercontent.com/assets/615386/5152966/4860cf36-71db-11e4-92ce-e88ae130ea0a.png)

![image2](http://cl.ly/YeYQ/Image.jpg)

Attempting to select any of these in Journaley causes exception to be thrown 

      ************** Exception Text **************
     System.ArgumentOutOfRangeException: Value of '1/1/0001 7:00:00 PM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
     Parameter name: Value
        at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
        at Journaley.Forms.MainForm.UpdateDateAndTextFromEntry() in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Forms\MainForm.cs:line 712
        at Journaley.Forms.MainForm.set_SelectedEntry(Entry value) in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Forms\MainForm.cs:line 239
        at Journaley.Forms.MainForm.EntryListBox_SelectedIndexChanged(Object sender, EventArgs e) in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Forms\MainForm.cs:line 1764
        at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
        at System.Windows.Forms.ListBox.WndProc(Message& m)
        at Journaley.Controls.EntryListBox.WndProc(Message& m) in c:\Users\Sammy\Documents\GitHub\Journaley\Journaley\Controls\EntryListBox.cs:line 192
        at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by yyoon** [comment]
I can't seem to reproduce this issue. Do you experience this often?

**Comment by sguergachi** [comment]
I'm still trying to figure out how to reproduce this. But as of now this bug can stay low priority.

**Comment by sguergachi** [comment]
I'm going to remove this from 2.0 milestone but keep it open in case anyone else runs into this issue.

**Comment by sguergachi** [comment]
Closing this for now.
